project:
  type: website

website:
  title: "openimaging.ai"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/openimagingai

format:
  html:
    theme: litera
    css: styles.css



